### ISSUE TITLE
Search for a Different alternative or remove David-DM

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OnlineTutor#38]
**Is your feature request related to a problem? Please describe.**
It's been noted that for several days [David-DM](https://david-dm.org/) is down. 

**Describe the solution you'd like**
David-DM seems not to be maintained anymore; so we should look for an alternative or just remove the badges from our [readme file ](https://github.com/python-sinhala-education-society/OnlineTutor/blob/master/README.md) (it's probably redundant since the CII badge already covers whether dependencies are upto date), 

**Describe alternatives you've considered**
We have opened an issue at David-DM; https://github.com/alanshaw/david/issues/153

**Comment by 1138-4EB** [comment]
You might find https://dependabot.com/ useful.

**Comment by SudharakaP** [comment]
@1138-4EB : Seems [David](https://david-dm.org/) is working again. Thanks for the suggestion; We use dependabot too actually (https://github.com/python-sinhala-education-society/OnlineTutor/pull/39). 

Closing this issue.
